FROM httpd:2.4
MAINTAINER iclientpy@supermap.com
ADD ./*.tar /usr/local/apache2/htdocs/
ADD http://ci.ispeco.com:90/guestAuth/repository/download/IClientPy_iClientPyCondaPkg/.lastSuccessful/iclientpy-conda-package.tar /usr/local/apache2/htdocs/conda/