FROM jupyterhub/jupyterhub:latest
MAINTAINER iclientpy@supermap.com

ADD pip.conf /root/.pip/pip.conf
RUN conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ \
&& conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ \
&& conda config --set show_channel_urls yes \
&& conda install python=3.6 lxml beautifulsoup4 geopandas fiona -y \
&& conda update --all \
&& conda clean -yt \
&& rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6* \
&& ln -s /opt/conda/lib/libstdc++.so.6.0.21 /usr/lib/x86_64-linux-gnu/libstdc++.so.6 \
&& ln -s /opt/conda/lib/libcurl.so.4.5.0 /usr/lib/x86_64-linux-gnu/libcurl.so.4
